In [20]:
import GEOparse

#gse: geo series
#gsm: geo sample
#gpl: geo platform

In [40]:
gse_ids = [
    "GSE10325",
    "GSE38351",
    "GSE39088",
    "GSE49454",
    "GSE32591",
    "GSE45291", 
    "GSE72747"
] #from the https://doi.org/10.1371/journal.pone.0208132 paper

In [22]:
gse = GEOparse.get_GEO("GSE10325")

14-Apr-2026 18:42:53 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:42:53 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:42:53 INFO GEOparse - Parsing ./GSE10325_family.soft.gz:
14-Apr-2026 18:42:53 DEBUG GEOparse - DATABASE: GeoMiame
14-Apr-2026 18:42:53 DEBUG GEOparse - SERIES: GSE10325
14-Apr-2026 18:42:53 DEBUG GEOparse - PLATFORM: GPL96
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260886
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260887
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260888
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260889
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260890
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260891
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260892
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260893
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260894
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260895
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260896
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260897
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260898
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260899
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260900
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260901
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260902
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260903
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260904
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260905
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260906
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260907
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260908
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260909
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260910
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260911
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260912
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260913
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260914
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260915
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260916
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260917
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260918
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260919
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260920
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260921
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260922
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260923
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260924
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260925
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260926
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260927
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260928
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260929
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260930
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260931
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260932
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260933
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260934
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260935
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260936
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260937
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260938
14-Apr-2026 18:42:54 DEBUG GEOparse - SAMPLE: GSM260939
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260940
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260941
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260942
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260943
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260944
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260945
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260946
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260947
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260948
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260949
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260950
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260951
14-Apr-2026 18:42:55 DEBUG GEOparse - SAMPLE: GSM260952

In [ ]:
platform = gse.gpls
platform_id = list(platform.keys())[0]

print(platform_id)

## TODO this platform has a column abs_call, which is supposed to be a classification of expressed, marginal or not expressed. That could be used instead, but not sure if it is common across platforms.

GPL96

In [24]:
genes_list = [
    "MTHFR", "TYMS", "MTR", "MTRR",
    "CYP1A1", "GSTM1", "GSTT1", "GSTP1",
    "TLR2", "TLR4", "TLR7", "TLR9",
    "STAT4"
] #from the rupashree et al paper

In [25]:
def process_platform(platform_id, genes_list):
    gpl = GEOparse.get_GEO(platform_id)

    # Get annotation table
    annot = gpl.table

    # Filter
    result = annot[annot["Gene Symbol"].isin(genes_list)]

    #create a dictionary mapping gene symbols to their corresponding probe IDs
    gene_to_probe = {}

    #initialise to empty list for each gene symbol
    for gene in genes_list:
        gene_to_probe[gene] = []

    for _, row in result.iterrows():
        gene_symbol = row["Gene Symbol"]
        probe_id = row["ID"]
        if gene_symbol not in gene_to_probe:
            gene_to_probe[gene_symbol] = []
        gene_to_probe[gene_symbol].append(probe_id)
    
    return gene_to_probe

def summarise_probes(gene_to_probe):
    print("Summarising probes for each gene, platform:", platform_id)
    for gene, probes in gene_to_probe.items():
        print(f"{gene}: {len(probes)} probes")

In [26]:
gene_to_probe = process_platform(platform_id, genes_list)
summarise_probes(gene_to_probe)

14-Apr-2026 18:42:55 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:42:55 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:42:55 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:42:55 DEBUG GEOparse - PLATFORM: GPL96

Summarising probes for each gene, platform: GPL96
MTHFR: 3 probes
TYMS: 2 probes
MTR: 1 probes
MTRR: 2 probes
CYP1A1: 1 probes
GSTM1: 2 probes
GSTT1: 1 probes
GSTP1: 1 probes
TLR2: 1 probes
TLR4: 1 probes
TLR7: 1 probes
TLR9: 0 probes
STAT4: 1 probes

In [27]:
## TODO some genes have multiple probes: they are taken average of . 
## TODO some genes have no probes: they are set to -1
# print(len(genes), len(genes_list))

In [29]:
# sample = list(gse.gsms.keys())[0]
# print(sample)

# gsm = gse.gsms[sample]
# print(gsm.table.head())
# table = gsm.table

# platform_id = gsm.metadata["platform_id"][0]
# print(gsm.metadata["platform_id"])
# if len(gsm.metadata["platform_id"]) > 1:
#     print(f"Found multiple platform IDs for sample {sample} in series {gse.name}: {gsm.metadata['platform_id']}")

# #get only the rows with the IDs we are interested in
# gsm_filtered = table[table["ID_REF"].isin(ids)]

# #number of rows in the filtered table should be the same as the number of genes we are interested in
# print(len(gsm_filtered), len(ids))

# gene_expression = {}
# for gene in genes_list:
#     gene_ids = gene_to_probe[gene]
#     gene_values = gsm_filtered[gsm_filtered["ID_REF"].isin(gene_ids)]["VALUE"].tolist()
#     if len(gene_values) > 0:
#         gene_expression[gene] = sum(gene_values) / len(gene_values)
#     else: # if there are no values for the gene, set it to None
#         gene_expression[gene] = None
#         print(f"Warning: No values found for gene {gene} in sample {sample} in series {gse.name}")
# print(gene_expression)

In [30]:
platform_id = gsm.metadata["platform_id"][0]
print(gsm.metadata["platform_id"])

['GPL96']

In [31]:
#get metadata for the gse
print(gsm.metadata)

{'title': ['healthy CD4 T cells 1'], 'geo_accession': ['GSM260886'], 'status': ['Public on Mar 01 2008'], 'submission_date': ['Jan 30 2008'], 'last_update_date': ['Apr 05 2011'], 'type': ['RNA'], 'channel_count': ['1'], 'source_name_ch1': ['Peripheral blood from healthy individuals'], 'organism_ch1': ['Homo sapiens'], 'taxid_ch1': ['9606'], 'characteristics_ch1': ['healthy donor'], 'treatment_protocol_ch1': ['PBMC were isolated, tagged with fluorochrome-conjugated antibodies to CD3, CD4, CD19 and CD33 for 30 min. PBMC were sorted into subsets on a Cytomation MoFlo cytometer into individual subsets. Purity of the populations was confirmed after sorting.'], 'molecule_ch1': ['total RNA'], 'extract_protocol_ch1': ['Qiagen Rneasy mini column; only high quality RNA samples as assessed by BioAnalyzer were hybridized to the GeneChips'], 'label_ch1': ['biotin'], 'label_protocol_ch1': ['Biotinylated cRNA was prepared according to the Affymetrix protocol from at least 5 ug of high quality RNA'], 'hyb_protocol': ['Following fragmentation, hybridization was carried out according to the Affymetrix Expression Analysis Technical Manual; only samples passing stringent quality control guidelines were assessed'], 'scan_protocol': ['Affymetrix arrays were scanned using the Affymetrix GeneChip Scanner 3000 System'], 'description': ['Gene expression data from freshly sorted cells'], 'data_processing': ['Data was analyzed with Microarray Suite version 5.0 (MAS 5.0) software using the Affymetrix default analysis settings and global scaling normalization methods.'], 'platform_id': ['GPL96'], 'contact_name': ['Laurie,S,Davis'], 'contact_email': ['laurie.davis@utsouthwestern.edu'], 'contact_phone': ['214-648-2201'], 'contact_laboratory': ['Davis'], 'contact_department': ['Internal Medicine'], 'contact_institute': ['UT Southwestern Medical Center'], 'contact_address': ['5323 Harry Hines Blvd'], 'contact_city': ['Dallas'], 'contact_state': ['TX'], 'contact_zip/postal_code': ['75390-8884'], 'contact_country': ['USA'], 'supplementary_file': ['ftp://ftp.ncbi.nlm.nih.gov/geo/samples/GSM260nnn/GSM260886/suppl/GSM260886.CEL.gz'], 'series_id': ['GSE10325'], 'data_row_count': ['22283']}

In [ ]:
def process_gsm(gsm, genes_list):
    """
    gsm is the sample object from GEOparse, 
    genes_list is the list of genes we are interested in
    """
    platform_id = gsm.metadata["platform_id"][0]

    if len(gsm.metadata["platform_id"]) > 1:
        print(f"ERROR\nFound multiple platform IDs for sample {sample} in series {gse.name}: {gsm.metadata['platform_id']}")


    if platform_id not in PROBES:
        gene_to_probe = process_platform(platform_id, genes_list)
        PROBES[platform_id] = gene_to_probe
    else:
        gene_to_probe = PROBES[platform_id]

    table = gsm.table
    gsm_filtered = table[table["ID_REF"].isin([probe for probes in gene_to_probe.values() for probe in probes])]

    gene_expression = {}
    for gene in genes_list:
        gene_ids = gene_to_probe[gene]
        gene_values = gsm_filtered[gsm_filtered["ID_REF"].isin(gene_ids)]["VALUE"].tolist()
        if len(gene_values) > 0:
            gene_expression[gene] = sum(gene_values) / len(gene_values)
        else: # if there are no values for the gene, set it to None
            gene_expression[gene] = -1
            print(f"WARNING: \nNo values found for gene {gene} in sample {sample} in series {gse.name}")
    return gene_expression

columns: GSE_ID, GSM_ID, GPL, title, [genes]

In [33]:
gsm.name
gsm.table.head()

           ID_REF  VALUE ABS_CALL
0  AFFX-BioB-5_at  226.2        P
1  AFFX-BioB-M_at  372.7        P
2  AFFX-BioB-3_at  140.7        P
3  AFFX-BioC-5_at  507.2        P
4  AFFX-BioC-3_at  332.3        P

In [34]:
process_gsm(gsm, genes_list)

14-Apr-2026 18:43:14 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:14 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:14 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:14 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325

{'MTHFR': 22.099999999999998,
 'TYMS': 97.95,
 'MTR': 385.7,
 'MTRR': 546.8000000000001,
 'CYP1A1': 27.8,
 'GSTM1': 505.5,
 'GSTT1': 13.0,
 'GSTP1': 422.7,
 'TLR2': 69.6,
 'TLR4': 23.5,
 'TLR7': 8.4,
 'TLR9': -1,
 'STAT4': 1215.0}

In [38]:
def get_platforms(list):
    ret_list = []

    for gse_id in gse_ids:
        gse  = GEOparse.get_GEO(gse_id)
        print(f"Series: {gse_id}, platforms: {gse.gpls.keys()}")
        ret_list.append(gse.gpls.keys())
    
    return ret_list

In [41]:
list_of_platforms = get_platforms(gse_ids)

PROBES = {}
for platform in list_of_platforms:
    gene_to_probe = process_platform(platform, genes_list)
    PROBES[platform] = gene_to_probe

14-Apr-2026 18:46:45 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:46:45 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:46:45 INFO GEOparse - Parsing ./GSE10325_family.soft.gz:
14-Apr-2026 18:46:45 DEBUG GEOparse - DATABASE: GeoMiame
14-Apr-2026 18:46:45 DEBUG GEOparse - SERIES: GSE10325
14-Apr-2026 18:46:45 DEBUG GEOparse - PLATFORM: GPL96
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260886
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260887
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260888
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260889
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260890
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260891
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260892
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260893
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260894
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260895
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260896
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260897
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260898
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260899
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260900
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260901
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260902
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260903
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260904
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260905
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260906
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260907
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260908
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260909
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260910
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260911
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260912
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260913
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260914
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260915
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260916
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260917
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260918
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260919
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260920
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260921
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260922
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260923
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260924
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260925
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260926
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260927
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260928
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260929
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260930
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260931
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260932
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260933
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260934
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260935
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260936
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260937
14-Apr-2026 18:46:46 DEBUG GEOparse - SAMPLE: GSM260938
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260939
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260940
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260941
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260942
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260943
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260944
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260945
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260946
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260947
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260948
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260949
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260950
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260951
14-Apr-2026 18:46:47 DEBUG GEOparse - SAMPLE: GSM260952
14-Apr-2026 18:46:47 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:46:47 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:46:47 INFO GEOparse - Parsing ./GSE38351_family.soft.gz:
14-Apr-2026 18:46:47 DEBUG GEOparse - DATABASE: GeoMiame
14-Apr-2026 18:46:47 DEBUG GEOparse - SERIES: GSE38351
14-Apr-2026 18:46:47 DEBUG GEOparse - PLATFORM: GPL96

Series: GSE10325, platforms: dict_keys(['GPL96'])

14-Apr-2026 18:46:47 DEBUG GEOparse - PLATFORM: GPL570
/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940450
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940451
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940452
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940453
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940454
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940455
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940456
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940457
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940458
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940459
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940460
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940461
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940462
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940463
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940464
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940465
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940466
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940467
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940468
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940469
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940470
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940471
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940472
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940473
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940474
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940475
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940476
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940477
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940478
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940479
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940480
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940481
14-Apr-2026 18:46:48 DEBUG GEOparse - SAMPLE: GSM940482
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940483
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940484
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940485
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940486
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940487
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940488
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940489
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940490
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940491
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940492
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940493
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940494
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940495
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940496
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940497
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940498
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940499
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940500
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940501
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940502
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940503
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940504
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940505
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940506
14-Apr-2026 18:46:49 DEBUG GEOparse - SAMPLE: GSM940507
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940508
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940509
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940510
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940511
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940512
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940513
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940514
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940515
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940516
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940517
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940518
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940519
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940520
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940521
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940522
14-Apr-2026 18:46:50 DEBUG GEOparse - SAMPLE: GSM940523
14-Apr-2026 18:46:50 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:46:50 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:46:50 INFO GEOparse - Parsing ./GSE39088_family.soft.gz:
14-Apr-2026 18:46:50 DEBUG GEOparse - DATABASE: GeoMiame
14-Apr-2026 18:46:50 DEBUG GEOparse - SERIES: GSE39088
14-Apr-2026 18:46:50 DEBUG GEOparse - PLATFORM: GPL570

Series: GSE38351, platforms: dict_keys(['GPL96', 'GPL570'])

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955680
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955681
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955682
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955683
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955684
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955685
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955686
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955687
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955688
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955689
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955690
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955691
14-Apr-2026 18:46:51 DEBUG GEOparse - SAMPLE: GSM955692
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955693
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955694
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955695
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955696
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955697
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955698
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955699
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955700
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955701
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955702
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955703
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955704
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955705
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955706
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955707
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955708
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955709
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955710
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955711
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955712
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955713
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955714
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955715
14-Apr-2026 18:46:52 DEBUG GEOparse - SAMPLE: GSM955716
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955717
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955718
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955719
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955720
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955721
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955722
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955723
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955724
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955725
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955726
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955727
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955728
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955729
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955730
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955731
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955732
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955733
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955734
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955735
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955736
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955737
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955738
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955739
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955740
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955741
14-Apr-2026 18:46:53 DEBUG GEOparse - SAMPLE: GSM955742
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955743
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955744
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955745
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955746
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955747
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955748
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955749
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955750
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955751
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955752
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955753
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955754
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955755
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955756
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955757
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955758
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955759
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955760
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955761
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955762
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955763
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955764
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955765
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955766
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955767
14-Apr-2026 18:46:54 DEBUG GEOparse - SAMPLE: GSM955768
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955769
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955770
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955771
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955772
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955773
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955774
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955775
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955776
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955777
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955778
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955779
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955780
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955781
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955782
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955783
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955784
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955785
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955786
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955787
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955788
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955789
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955790
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955791
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955792
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955793
14-Apr-2026 18:46:55 DEBUG GEOparse - SAMPLE: GSM955794
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955795
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955796
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955797
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955798
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955799
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955800
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955801
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955802
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955803
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955804
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955805
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955806
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955807
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955808
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955809
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955810
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955811
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955812
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955813
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955814
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955815
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955816
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955817
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955818
14-Apr-2026 18:46:56 DEBUG GEOparse - SAMPLE: GSM955819
14-Apr-2026 18:46:57 DEBUG GEOparse - SAMPLE: GSM955820
14-Apr-2026 18:46:57 DEBUG GEOparse - SAMPLE: GSM955821
14-Apr-2026 18:46:57 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:46:57 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:46:57 INFO GEOparse - Parsing ./GSE49454_family.soft.gz:
14-Apr-2026 18:46:57 DEBUG GEOparse - DATABASE: GeoMiame
14-Apr-2026 18:46:57 DEBUG GEOparse - SERIES: GSE49454
14-Apr-2026 18:46:57 DEBUG GEOparse - PLATFORM: GPL10558

Series: GSE39088, platforms: dict_keys(['GPL570'])

14-Apr-2026 18:46:57 DEBUG GEOparse - SAMPLE: GSM1199352
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199353
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199354
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199355
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199356
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199357
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199358
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199359
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199360
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199361
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199362
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199363
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199364
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199365
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199367
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199369
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199373
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199376
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199379
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199381
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199384
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199386
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199388
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199391
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199394
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199396
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199398
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199399
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199400
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199401
14-Apr-2026 18:46:58 DEBUG GEOparse - SAMPLE: GSM1199402
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199403
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199404
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199405
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199406
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199407
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199408
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199409
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199410
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199411
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199412
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199413
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199414
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199415
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199416
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199417
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199418
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199419
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199420
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199421
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199422
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199423
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199424
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199425
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199426
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199427
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199428
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199429
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199430
14-Apr-2026 18:46:59 DEBUG GEOparse - SAMPLE: GSM1199431
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199432
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199433
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199434
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199435
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199436
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199437
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199438
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199439
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199440
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199441
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199442
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199443
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199444
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199445
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199446
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199447
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199448
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199449
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199450
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199451
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199452
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199453
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199454
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199455
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199456
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199457
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199458
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199459
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199460
14-Apr-2026 18:47:00 DEBUG GEOparse - SAMPLE: GSM1199461
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199462
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199463
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199464
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199465
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199466
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199467
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199468
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199469
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199470
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199471
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199472
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199473
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199474
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199475
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199476
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199477
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199478
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199479
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199480
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199481
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199482
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199483
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199484
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199485
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199486
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199487
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199488
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199489
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199490
14-Apr-2026 18:47:01 DEBUG GEOparse - SAMPLE: GSM1199491
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199492
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199493
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199494
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199495
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199496
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199497
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199498
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199499
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199500
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199501
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199502
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199503
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199504
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199505
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199506
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199507
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199508
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199509
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199510
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199511
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199512
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199513
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199514
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199515
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199516
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199517
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199518
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199519
14-Apr-2026 18:47:02 DEBUG GEOparse - SAMPLE: GSM1199520
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199521
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199522
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199523
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199524
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199525
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199526
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199527
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199528
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199529
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199530
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199531
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199532
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199533
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199534
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199535
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199536
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199537
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199538
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199539
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199540
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199541
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199542
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199543
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199544
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199545
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199546
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199547
14-Apr-2026 18:47:03 DEBUG GEOparse - SAMPLE: GSM1199548
14-Apr-2026 18:47:04 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:47:04 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:47:04 INFO GEOparse - Parsing ./GSE32591_family.soft.gz:
14-Apr-2026 18:47:04 DEBUG GEOparse - DATABASE: GeoMiame
14-Apr-2026 18:47:04 DEBUG GEOparse - SERIES: GSE32591
14-Apr-2026 18:47:04 DEBUG GEOparse - PLATFORM: GPL14663
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807842
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807843
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807844
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807845
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807846
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807847
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807848
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807849
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807850
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807851
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807852
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807853
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807854
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807855
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807856
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807857
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807858
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807859
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807860
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807861
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807862

Series: GSE49454, platforms: dict_keys(['GPL10558'])

14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807863
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807864
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807865
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807866
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807867
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807868
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807869
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807870
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807871
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807872
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807873
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807874
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807875
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807876
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807877
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807878
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807879
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807880
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807881
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807882
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807883
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807884
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807885
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807886
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807887
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807888
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807889
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807890
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807891
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807892
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807893
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807894
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807895
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807896
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807897
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807898
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807899
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807900
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807901
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807902
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807903
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807904
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807905
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807906
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807907
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807908
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807909
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807910
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807911
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807912
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807913
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807914
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807915
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807916
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807917
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807918
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807919
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807920
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807921
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807922
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807923
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807924
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807925
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807926
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807927
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807928
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807929
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807930
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807931
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807932
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807933
14-Apr-2026 18:47:04 DEBUG GEOparse - SAMPLE: GSM807934
14-Apr-2026 18:47:05 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:47:05 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:47:05 INFO GEOparse - Parsing ./GSE45291_family.soft.gz:
14-Apr-2026 18:47:05 DEBUG GEOparse - DATABASE: GeoMiame
14-Apr-2026 18:47:05 DEBUG GEOparse - SERIES: GSE45291
14-Apr-2026 18:47:05 DEBUG GEOparse - PLATFORM: GPL13158

Series: GSE32591, platforms: dict_keys(['GPL14663'])

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:47:05 DEBUG GEOparse - SAMPLE: GSM1100843
14-Apr-2026 18:47:05 DEBUG GEOparse - SAMPLE: GSM1100844
14-Apr-2026 18:47:05 DEBUG GEOparse - SAMPLE: GSM1100845
14-Apr-2026 18:47:05 DEBUG GEOparse - SAMPLE: GSM1100846
14-Apr-2026 18:47:05 DEBUG GEOparse - SAMPLE: GSM1100847
14-Apr-2026 18:47:05 DEBUG GEOparse - SAMPLE: GSM1100848
14-Apr-2026 18:47:05 DEBUG GEOparse - SAMPLE: GSM1100849
14-Apr-2026 18:47:05 DEBUG GEOparse - SAMPLE: GSM1100850
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100851
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100852
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100853
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100854
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100855
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100856
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100857
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100858
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100859
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100860
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100861
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100862
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100863
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100864
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100865
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100866
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100867
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100868
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100869
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100870
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100871
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100872
14-Apr-2026 18:47:06 DEBUG GEOparse - SAMPLE: GSM1100873
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100874
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100875
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100876
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100877
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100878
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100879
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100880
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100881
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100882
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100883
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100884
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100885
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100886
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100887
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100888
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100889
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100890
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100891
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100892
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100893
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100894
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100895
14-Apr-2026 18:47:07 DEBUG GEOparse - SAMPLE: GSM1100896
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100897
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100898
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100899
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100900
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100901
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100902
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100903
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100904
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100905
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100906
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100907
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100908
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100909
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100910
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100911
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100912
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100913
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100914
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100915
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100916
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100917
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100918
14-Apr-2026 18:47:08 DEBUG GEOparse - SAMPLE: GSM1100919
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100920
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100921
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100922
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100923
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100924
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100925
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100926
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100927
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100928
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100929
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100930
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100931
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100932
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100933
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100934
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100935
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100936
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100937
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100938
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100939
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100940
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100941
14-Apr-2026 18:47:09 DEBUG GEOparse - SAMPLE: GSM1100942
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100943
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100944
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100945
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100946
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100947
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100948
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100949
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100950
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100951
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100952
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100953
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100954
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100955
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100956
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100957
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100958
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100959
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100960
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100961
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100962
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100963
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100964
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100965
14-Apr-2026 18:47:10 DEBUG GEOparse - SAMPLE: GSM1100966
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100967
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100968
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100969
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100970
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100971
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100972
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100973
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100974
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100975
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100976
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100977
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100978
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100979
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100980
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100981
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100982
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100983
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100984
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100985
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100986
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100987
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100988
14-Apr-2026 18:47:11 DEBUG GEOparse - SAMPLE: GSM1100989
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100990
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100991
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100992
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100993
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100994
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100995
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100996
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100997
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100998
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1100999
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101000
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101001
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101002
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101003
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101004
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101005
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101006
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101007
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101008
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101009
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101010
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101011
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101012
14-Apr-2026 18:47:12 DEBUG GEOparse - SAMPLE: GSM1101013
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101014
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101015
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101016
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101017
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101018
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101019
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101020
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101021
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101022
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101023
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101024
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101025
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101026
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101027
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101028
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101029
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101030
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101031
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101032
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101033
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101034
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101035
14-Apr-2026 18:47:13 DEBUG GEOparse - SAMPLE: GSM1101036
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101037
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101038
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101039
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101040
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101041
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101042
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101043
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101044
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101045
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101046
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101047
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101048
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101049
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101050
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101051
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101052
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101053
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101054
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101055
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101056
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101057
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101058
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101059
14-Apr-2026 18:47:14 DEBUG GEOparse - SAMPLE: GSM1101060
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101061
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101062
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101063
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101064
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101065
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101066
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101067
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101068
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101069
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101070
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101071
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101072
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101073
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101074
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101075
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101076
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101077
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101078
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101079
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101080
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101081
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101082
14-Apr-2026 18:47:15 DEBUG GEOparse - SAMPLE: GSM1101083
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101084
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101085
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101086
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101087
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101088
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101089
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101090
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101091
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101092
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101093
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101094
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101095
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101096
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101097
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101098
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101099
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101100
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101101
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101102
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101103
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101104
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101105
14-Apr-2026 18:47:16 DEBUG GEOparse - SAMPLE: GSM1101106
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101107
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101108
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101109
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101110
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101111
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101112
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101113
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101114
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101115
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101116
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101117
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101118
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101119
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101120
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101121
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101122
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101123
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101124
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101125
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101126
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101127
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101128
14-Apr-2026 18:47:17 DEBUG GEOparse - SAMPLE: GSM1101129
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101130
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101131
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101132
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101133
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101134
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101135
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101136
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101137
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101138
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101139
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101140
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101141
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101142
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101143
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101144
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101145
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101146
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101147
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101148
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101149
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101150
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101151
14-Apr-2026 18:47:18 DEBUG GEOparse - SAMPLE: GSM1101152
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101153
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101154
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101155
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101156
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101157
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101158
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101159
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101160
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101161
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101162
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101163
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101164
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101165
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101166
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101167
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101168
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101169
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101170
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101171
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101172
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101173
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101174
14-Apr-2026 18:47:19 DEBUG GEOparse - SAMPLE: GSM1101175
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101176
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101177
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101178
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101179
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101180
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101181
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101182
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101183
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101184
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101185
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101186
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101187
14-Apr-2026 18:47:20 DEBUG GEOparse - SAMPLE: GSM1101188

Series: GSE45291, platforms: dict_keys(['GPL13158'])

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869396
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869397
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869398
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869399
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869400
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869401
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869402
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869403
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869404
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869405
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869406
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869407
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869408
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869409
14-Apr-2026 18:47:41 DEBUG GEOparse - SAMPLE: GSM1869410
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869411
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869412
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869413
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869414
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869415
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869416
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869417
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869418
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869419
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869420
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869421
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869422
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869423
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869424
14-Apr-2026 18:47:42 DEBUG GEOparse - SAMPLE: GSM1869425

Series: GSE72747, platforms: dict_keys(['GPL570'])

AttributeError: 'dict_keys' object has no attribute 'upper'

In [35]:
def process_gse(gse_id, genes_list):
    gse = GEOparse.get_GEO(gse_id)
    
    samples = gse.gsms.keys()
    for sample in samples:
        gsm = gse.gsms[sample]
        gene_expression = process_gsm(gsm, genes_list)
        print(f"Gene expression for sample {sample} in series {gse_id}: {gene_expression}")

In [36]:
process_gse(gse_ids[1], genes_list)

14-Apr-2026 18:43:15 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:15 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:15 INFO GEOparse - Parsing ./GSE38351_family.soft.gz:
14-Apr-2026 18:43:15 DEBUG GEOparse - DATABASE: GeoMiame
14-Apr-2026 18:43:15 DEBUG GEOparse - SERIES: GSE38351
14-Apr-2026 18:43:15 DEBUG GEOparse - PLATFORM: GPL96
14-Apr-2026 18:43:15 DEBUG GEOparse - PLATFORM: GPL570
/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940450
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940451
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940452
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940453
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940454
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940455
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940456
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940457
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940458
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940459
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940460
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940461
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940462
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940463
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940464
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940465
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940466
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940467
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940468
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940469
14-Apr-2026 18:43:16 DEBUG GEOparse - SAMPLE: GSM940470
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940471
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940472
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940473
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940474
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940475
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940476
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940477
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940478
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940479
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940480
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940481
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940482
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940483
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940484
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940485
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940486
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940487
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940488
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940489
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940490
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940491
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940492
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940493
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940494
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940495
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940496
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940497
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940498
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940499
14-Apr-2026 18:43:17 DEBUG GEOparse - SAMPLE: GSM940500
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940501
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940502
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940503
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940504
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940505
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940506
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940507
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940508
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940509
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940510
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940511
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940512
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940513
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940514
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940515
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940516
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940517
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940518
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940519
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940520
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940521
14-Apr-2026 18:43:18 DEBUG GEOparse - SAMPLE: GSM940522
14-Apr-2026 18:43:19 DEBUG GEOparse - SAMPLE: GSM940523
14-Apr-2026 18:43:19 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:19 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:19 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:19 DEBUG GEOparse - PLATFORM: GPL96
14-Apr-2026 18:43:19 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:19 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:19 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:19 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940450 in series GSE38351: {'MTHFR': 22.333333333333332, 'TYMS': 27.65, 'MTR': 127.3, 'MTRR': 91.19999999999999, 'CYP1A1': 16.3, 'GSTM1': 88.05, 'GSTT1': 13.0, 'GSTP1': 826.1, 'TLR2': 2058.7, 'TLR4': 541.6, 'TLR7': 316.4, 'TLR9': -1, 'STAT4': 108.0}

14-Apr-2026 18:43:19 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:19 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:19 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:19 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940451 in series GSE38351: {'MTHFR': 12.199999999999998, 'TYMS': 37.75, 'MTR': 103.2, 'MTRR': 118.1, 'CYP1A1': 3.1, 'GSTM1': 118.35000000000001, 'GSTT1': 8.2, 'GSTP1': 770.0, 'TLR2': 1523.8, 'TLR4': 746.3, 'TLR7': 273.1, 'TLR9': -1, 'STAT4': 92.7}

14-Apr-2026 18:43:20 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:20 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:20 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:20 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940452 in series GSE38351: {'MTHFR': 10.266666666666667, 'TYMS': 40.75, 'MTR': 147.2, 'MTRR': 108.8, 'CYP1A1': 9.5, 'GSTM1': 71.15, 'GSTT1': 5.9, 'GSTP1': 583.0, 'TLR2': 1398.5, 'TLR4': 704.7, 'TLR7': 424.0, 'TLR9': -1, 'STAT4': 90.6}

14-Apr-2026 18:43:20 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:20 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:20 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:20 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940453 in series GSE38351: {'MTHFR': 17.53333333333333, 'TYMS': 36.5, 'MTR': 122.1, 'MTRR': 141.5, 'CYP1A1': 20.8, 'GSTM1': 116.95, 'GSTT1': 7.4, 'GSTP1': 620.5, 'TLR2': 2057.5, 'TLR4': 833.9, 'TLR7': 244.8, 'TLR9': -1, 'STAT4': 67.4}

14-Apr-2026 18:43:21 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:21 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:21 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:21 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940454 in series GSE38351: {'MTHFR': 13.933333333333332, 'TYMS': 17.25, 'MTR': 100.5, 'MTRR': 141.8, 'CYP1A1': 5.2, 'GSTM1': 80.2, 'GSTT1': 4.8, 'GSTP1': 853.4, 'TLR2': 1724.3, 'TLR4': 815.5, 'TLR7': 323.1, 'TLR9': -1, 'STAT4': 69.2}

14-Apr-2026 18:43:21 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:21 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:21 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:21 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940455 in series GSE38351: {'MTHFR': 30.86666666666667, 'TYMS': 35.75, 'MTR': 88.1, 'MTRR': 140.0, 'CYP1A1': 8.9, 'GSTM1': 69.65, 'GSTT1': 7.3, 'GSTP1': 874.7, 'TLR2': 1775.4, 'TLR4': 899.6, 'TLR7': 173.8, 'TLR9': -1, 'STAT4': 86.8}

14-Apr-2026 18:43:21 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:21 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:21 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:21 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940456 in series GSE38351: {'MTHFR': 13.733333333333334, 'TYMS': 29.65, 'MTR': 106.9, 'MTRR': 102.14999999999999, 'CYP1A1': 26.1, 'GSTM1': 167.95, 'GSTT1': 3.9, 'GSTP1': 770.3, 'TLR2': 1829.4, 'TLR4': 688.2, 'TLR7': 288.5, 'TLR9': -1, 'STAT4': 84.8}

14-Apr-2026 18:43:22 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:22 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:22 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:22 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940457 in series GSE38351: {'MTHFR': 23.03333333333333, 'TYMS': 23.0, 'MTR': 91.7, 'MTRR': 97.55000000000001, 'CYP1A1': 19.4, 'GSTM1': 74.9, 'GSTT1': 14.3, 'GSTP1': 843.2, 'TLR2': 2035.6, 'TLR4': 745.1, 'TLR7': 494.4, 'TLR9': -1, 'STAT4': 79.9}

14-Apr-2026 18:43:22 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:22 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:22 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:22 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940458 in series GSE38351: {'MTHFR': 8.6, 'TYMS': 25.7, 'MTR': 97.5, 'MTRR': 111.65, 'CYP1A1': 9.3, 'GSTM1': 84.45, 'GSTT1': 7.7, 'GSTP1': 779.9, 'TLR2': 1296.4, 'TLR4': 601.0, 'TLR7': 501.2, 'TLR9': -1, 'STAT4': 55.8}

14-Apr-2026 18:43:23 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:23 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:23 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:23 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940459 in series GSE38351: {'MTHFR': 17.633333333333333, 'TYMS': 28.35, 'MTR': 62.7, 'MTRR': 115.35000000000001, 'CYP1A1': 14.9, 'GSTM1': 34.0, 'GSTT1': 8.7, 'GSTP1': 713.3, 'TLR2': 1257.7, 'TLR4': 598.9, 'TLR7': 74.2, 'TLR9': -1, 'STAT4': 39.7}

14-Apr-2026 18:43:23 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:23 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:23 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:23 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940460 in series GSE38351: {'MTHFR': 35.53333333333333, 'TYMS': 33.65, 'MTR': 157.2, 'MTRR': 122.65, 'CYP1A1': 29.3, 'GSTM1': 115.39999999999999, 'GSTT1': 19.2, 'GSTP1': 651.3, 'TLR2': 1723.8, 'TLR4': 678.4, 'TLR7': 390.9, 'TLR9': -1, 'STAT4': 42.0}

14-Apr-2026 18:43:23 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:23 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:23 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:23 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940461 in series GSE38351: {'MTHFR': 6.5, 'TYMS': 19.2, 'MTR': 146.8, 'MTRR': 119.25, 'CYP1A1': 17.9, 'GSTM1': 68.0, 'GSTT1': 5.1, 'GSTP1': 895.5, 'TLR2': 2690.9, 'TLR4': 710.0, 'TLR7': 202.6, 'TLR9': -1, 'STAT4': 29.0}

14-Apr-2026 18:43:24 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:24 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:24 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:24 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940462 in series GSE38351: {'MTHFR': 35.13333333333333, 'TYMS': 21.05, 'MTR': 110.7, 'MTRR': 119.0, 'CYP1A1': 4.4, 'GSTM1': 85.55, 'GSTT1': 29.6, 'GSTP1': 755.6, 'TLR2': 2022.8, 'TLR4': 973.1, 'TLR7': 231.8, 'TLR9': -1, 'STAT4': 10.2}

14-Apr-2026 18:43:24 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:24 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:24 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:24 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940463 in series GSE38351: {'MTHFR': 12.399999999999999, 'TYMS': 15.25, 'MTR': 152.3, 'MTRR': 104.85, 'CYP1A1': 14.5, 'GSTM1': 46.0, 'GSTT1': 9.3, 'GSTP1': 1070.5, 'TLR2': 2279.2, 'TLR4': 1055.4, 'TLR7': 198.7, 'TLR9': -1, 'STAT4': 53.3}

14-Apr-2026 18:43:25 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:25 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:25 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:25 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940464 in series GSE38351: {'MTHFR': 14.133333333333333, 'TYMS': 19.549999999999997, 'MTR': 91.1, 'MTRR': 109.35, 'CYP1A1': 19.6, 'GSTM1': 138.45, 'GSTT1': 8.3, 'GSTP1': 969.6, 'TLR2': 1350.5, 'TLR4': 603.2, 'TLR7': 209.7, 'TLR9': -1, 'STAT4': 44.7}

14-Apr-2026 18:43:25 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:25 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:25 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:25 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940465 in series GSE38351: {'MTHFR': 5.366666666666666, 'TYMS': 21.25, 'MTR': 124.2, 'MTRR': 114.25, 'CYP1A1': 16.1, 'GSTM1': 76.4, 'GSTT1': 24.2, 'GSTP1': 1116.8, 'TLR2': 1418.3, 'TLR4': 569.3, 'TLR7': 188.8, 'TLR9': -1, 'STAT4': 48.4}

14-Apr-2026 18:43:25 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:25 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:25 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:25 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940466 in series GSE38351: {'MTHFR': 8.866666666666665, 'TYMS': 19.75, 'MTR': 84.9, 'MTRR': 131.2, 'CYP1A1': 10.5, 'GSTM1': 69.75, 'GSTT1': 20.0, 'GSTP1': 904.7, 'TLR2': 2146.5, 'TLR4': 500.7, 'TLR7': 191.0, 'TLR9': -1, 'STAT4': 45.4}

14-Apr-2026 18:43:26 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:26 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:26 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:26 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940467 in series GSE38351: {'MTHFR': 4.966666666666666, 'TYMS': 26.15, 'MTR': 107.4, 'MTRR': 130.3, 'CYP1A1': 5.3, 'GSTM1': 116.6, 'GSTT1': 46.1, 'GSTP1': 1046.2, 'TLR2': 1247.2, 'TLR4': 829.1, 'TLR7': 133.4, 'TLR9': -1, 'STAT4': 69.5}

14-Apr-2026 18:43:26 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:26 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:26 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:26 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940468 in series GSE38351: {'MTHFR': 14.799999999999999, 'TYMS': 36.05, 'MTR': 79.4, 'MTRR': 109.5, 'CYP1A1': 24.4, 'GSTM1': 144.65, 'GSTT1': 12.4, 'GSTP1': 1093.5, 'TLR2': 1525.6, 'TLR4': 692.3, 'TLR7': 127.8, 'TLR9': -1, 'STAT4': 59.7}

14-Apr-2026 18:43:27 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:27 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:27 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:27 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940469 in series GSE38351: {'MTHFR': 8.166666666666666, 'TYMS': 19.3, 'MTR': 94.5, 'MTRR': 221.75, 'CYP1A1': 24.8, 'GSTM1': 200.25, 'GSTT1': 31.1, 'GSTP1': 1090.7, 'TLR2': 1952.2, 'TLR4': 908.9, 'TLR7': 135.1, 'TLR9': -1, 'STAT4': 61.1}

14-Apr-2026 18:43:27 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:27 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:27 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:27 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940470 in series GSE38351: {'MTHFR': 10.466666666666667, 'TYMS': 43.4, 'MTR': 101.4, 'MTRR': 90.0, 'CYP1A1': 20.2, 'GSTM1': 107.55, 'GSTT1': 11.6, 'GSTP1': 945.0, 'TLR2': 1565.2, 'TLR4': 255.7, 'TLR7': 324.4, 'TLR9': -1, 'STAT4': 83.7}

14-Apr-2026 18:43:28 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:28 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:28 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:28 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940471 in series GSE38351: {'MTHFR': 8.133333333333335, 'TYMS': 30.55, 'MTR': 106.4, 'MTRR': 116.1, 'CYP1A1': 11.5, 'GSTM1': 148.1, 'GSTT1': 13.3, 'GSTP1': 755.9, 'TLR2': 974.2, 'TLR4': 254.5, 'TLR7': 241.6, 'TLR9': -1, 'STAT4': 62.7}

14-Apr-2026 18:43:28 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:28 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:28 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:28 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940472 in series GSE38351: {'MTHFR': 6.533333333333334, 'TYMS': 30.85, 'MTR': 119.1, 'MTRR': 103.15, 'CYP1A1': 26.2, 'GSTM1': 73.1, 'GSTT1': 54.5, 'GSTP1': 1333.5, 'TLR2': 1125.8, 'TLR4': 580.6, 'TLR7': 154.9, 'TLR9': -1, 'STAT4': 55.2}

14-Apr-2026 18:43:28 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:28 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:28 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:28 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940473 in series GSE38351: {'MTHFR': 9.333333333333334, 'TYMS': 38.2, 'MTR': 89.2, 'MTRR': 106.5, 'CYP1A1': 19.2, 'GSTM1': 195.35000000000002, 'GSTT1': 13.4, 'GSTP1': 1268.0, 'TLR2': 1321.9, 'TLR4': 362.4, 'TLR7': 225.4, 'TLR9': -1, 'STAT4': 96.9}

14-Apr-2026 18:43:29 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:29 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:29 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:29 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940474 in series GSE38351: {'MTHFR': 9.633333333333335, 'TYMS': 20.85, 'MTR': 102.7, 'MTRR': 116.0, 'CYP1A1': 9.1, 'GSTM1': 84.80000000000001, 'GSTT1': 8.3, 'GSTP1': 1099.0, 'TLR2': 1015.4, 'TLR4': 460.6, 'TLR7': 188.7, 'TLR9': -1, 'STAT4': 64.7}

14-Apr-2026 18:43:29 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:29 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:29 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:29 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940475 in series GSE38351: {'MTHFR': 28.266666666666666, 'TYMS': 14.95, 'MTR': 110.3, 'MTRR': 123.60000000000001, 'CYP1A1': 7.1, 'GSTM1': 92.1, 'GSTT1': 9.3, 'GSTP1': 1307.5, 'TLR2': 1216.8, 'TLR4': 744.7, 'TLR7': 192.0, 'TLR9': -1, 'STAT4': 55.7}

14-Apr-2026 18:43:30 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:30 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:30 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:30 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940476 in series GSE38351: {'MTHFR': 18.866666666666667, 'TYMS': 29.849999999999998, 'MTR': 128.0, 'MTRR': 101.6, 'CYP1A1': 4.5, 'GSTM1': 182.15, 'GSTT1': 11.4, 'GSTP1': 1106.7, 'TLR2': 1101.3, 'TLR4': 726.4, 'TLR7': 233.9, 'TLR9': -1, 'STAT4': 82.5}

14-Apr-2026 18:43:30 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:30 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:30 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:30 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940477 in series GSE38351: {'MTHFR': 15.633333333333335, 'TYMS': 24.85, 'MTR': 140.9, 'MTRR': 125.65, 'CYP1A1': 14.5, 'GSTM1': 141.5, 'GSTT1': 6.8, 'GSTP1': 1189.8, 'TLR2': 1283.9, 'TLR4': 718.2, 'TLR7': 280.2, 'TLR9': -1, 'STAT4': 74.3}

14-Apr-2026 18:43:30 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:30 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:30 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:30 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940478 in series GSE38351: {'MTHFR': 8.799999999999999, 'TYMS': 33.25, 'MTR': 102.0, 'MTRR': 142.55, 'CYP1A1': 5.9, 'GSTM1': 191.55, 'GSTT1': 8.0, 'GSTP1': 891.2, 'TLR2': 1139.4, 'TLR4': 726.1, 'TLR7': 241.7, 'TLR9': -1, 'STAT4': 76.0}

14-Apr-2026 18:43:31 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:31 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:31 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:31 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940479 in series GSE38351: {'MTHFR': 11.033333333333333, 'TYMS': 32.449999999999996, 'MTR': 110.7, 'MTRR': 149.15, 'CYP1A1': 26.3, 'GSTM1': 171.14999999999998, 'GSTT1': 11.8, 'GSTP1': 836.9, 'TLR2': 1090.0, 'TLR4': 336.3, 'TLR7': 193.3, 'TLR9': -1, 'STAT4': 93.8}

14-Apr-2026 18:43:31 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:31 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:31 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:31 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940480 in series GSE38351: {'MTHFR': 14.1, 'TYMS': 46.3, 'MTR': 71.3, 'MTRR': 100.95, 'CYP1A1': 9.6, 'GSTM1': 121.4, 'GSTT1': 12.9, 'GSTP1': 851.0, 'TLR2': 849.2, 'TLR4': 358.6, 'TLR7': 118.1, 'TLR9': -1, 'STAT4': 81.5}

14-Apr-2026 18:43:32 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:32 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:32 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:32 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940481 in series GSE38351: {'MTHFR': 15.766666666666667, 'TYMS': 20.400000000000002, 'MTR': 60.7, 'MTRR': 104.15, 'CYP1A1': 10.2, 'GSTM1': 97.65, 'GSTT1': 7.2, 'GSTP1': 1004.0, 'TLR2': 934.0, 'TLR4': 568.7, 'TLR7': 152.9, 'TLR9': -1, 'STAT4': 76.5}

14-Apr-2026 18:43:32 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:32 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:32 INFO GEOparse - Parsing ./GPL96.txt:
14-Apr-2026 18:43:32 DEBUG GEOparse - PLATFORM: GPL96

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940482 in series GSE38351: {'MTHFR': 14.566666666666668, 'TYMS': 15.9, 'MTR': 103.6, 'MTRR': 106.44999999999999, 'CYP1A1': 11.5, 'GSTM1': 123.15, 'GSTT1': 9.0, 'GSTP1': 1155.8, 'TLR2': 1195.5, 'TLR4': 651.2, 'TLR7': 210.9, 'TLR9': -1, 'STAT4': 86.0}

14-Apr-2026 18:43:32 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:32 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:32 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:32 DEBUG GEOparse - PLATFORM: GPL570

WARNING:
No values found for gene TLR9 in sample GSM260886 in series GSE10325
Gene expression for sample GSM940483 in series GSE38351: {'MTHFR': 16.266666666666666, 'TYMS': 18.15, 'MTR': 95.4, 'MTRR': 144.05, 'CYP1A1': 4.1, 'GSTM1': 142.8, 'GSTT1': 28.6, 'GSTP1': 941.5, 'TLR2': 1261.7, 'TLR4': 642.9, 'TLR7': 211.3, 'TLR9': -1, 'STAT4': 73.0}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:33 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:33 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:33 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:33 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940484 in series GSE38351: {'MTHFR': 132.7, 'TYMS': 9.033333333333333, 'MTR': 230.14999999999998, 'MTRR': 327.25, 'CYP1A1': 5.0, 'GSTM1': 105.6, 'GSTT1': 48.65, 'GSTP1': 2498.1, 'TLR2': 4331.2, 'TLR4': 1012.4, 'TLR7': 305.55, 'TLR9': 2.9, 'STAT4': 17.0}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:34 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:34 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:34 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:34 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940485 in series GSE38351: {'MTHFR': 140.98, 'TYMS': 16.633333333333333, 'MTR': 262.95, 'MTRR': 340.4, 'CYP1A1': 3.8, 'GSTM1': 50.3, 'GSTT1': 30.05, 'GSTP1': 1670.0, 'TLR2': 6041.6, 'TLR4': 661.6, 'TLR7': 53.300000000000004, 'TLR9': 15.0, 'STAT4': 8.1}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:35 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:35 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:35 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:35 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940486 in series GSE38351: {'MTHFR': 132.18, 'TYMS': 14.233333333333334, 'MTR': 227.55, 'MTRR': 412.95, 'CYP1A1': 26.4, 'GSTM1': 26.3, 'GSTT1': 16.35, 'GSTP1': 2423.8, 'TLR2': 3690.8, 'TLR4': 817.2, 'TLR7': 299.75, 'TLR9': 33.1, 'STAT4': 52.1}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:36 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:36 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:36 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:36 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940487 in series GSE38351: {'MTHFR': 164.92000000000002, 'TYMS': 5.966666666666668, 'MTR': 286.0, 'MTRR': 348.20000000000005, 'CYP1A1': 19.7, 'GSTM1': 51.099999999999994, 'GSTT1': 4.3, 'GSTP1': 3408.7, 'TLR2': 3279.3, 'TLR4': 950.0, 'TLR7': 398.65, 'TLR9': 17.9, 'STAT4': 59.2}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:37 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:37 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:37 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:37 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940488 in series GSE38351: {'MTHFR': 122.81999999999998, 'TYMS': 8.7, 'MTR': 142.04999999999998, 'MTRR': 276.6, 'CYP1A1': 3.1, 'GSTM1': 147.65, 'GSTT1': 48.9, 'GSTP1': 3561.3, 'TLR2': 10185.1, 'TLR4': 513.8499999999999, 'TLR7': 299.25, 'TLR9': 25.6, 'STAT4': 289.8}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:38 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:38 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:38 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:38 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940489 in series GSE38351: {'MTHFR': 82.11999999999999, 'TYMS': 16.8, 'MTR': 164.29999999999998, 'MTRR': 285.75, 'CYP1A1': 26.1, 'GSTM1': 37.9, 'GSTT1': 2.8499999999999996, 'GSTP1': 2641.2, 'TLR2': 9094.1, 'TLR4': 524.05, 'TLR7': 143.85000000000002, 'TLR9': 3.4, 'STAT4': 677.2}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:38 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:38 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:38 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:38 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940490 in series GSE38351: {'MTHFR': 76.58, 'TYMS': 5.666666666666667, 'MTR': 170.89999999999998, 'MTRR': 286.6, 'CYP1A1': 38.7, 'GSTM1': 56.0, 'GSTT1': 54.849999999999994, 'GSTP1': 3844.3, 'TLR2': 10626.4, 'TLR4': 403.25000000000006, 'TLR7': 383.95000000000005, 'TLR9': 16.2, 'STAT4': 555.8}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:39 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:39 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:39 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:39 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940491 in series GSE38351: {'MTHFR': 102.96, 'TYMS': 4.966666666666666, 'MTR': 179.15, 'MTRR': 232.3, 'CYP1A1': 17.2, 'GSTM1': 76.15, 'GSTT1': 43.050000000000004, 'GSTP1': 3096.7, 'TLR2': 2374.2, 'TLR4': 720.6500000000001, 'TLR7': 706.0, 'TLR9': 3.7, 'STAT4': 47.2}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:40 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:40 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:40 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:40 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940492 in series GSE38351: {'MTHFR': 111.97999999999999, 'TYMS': 5.933333333333334, 'MTR': 217.55, 'MTRR': 219.29999999999998, 'CYP1A1': 7.0, 'GSTM1': 64.35, 'GSTT1': 38.349999999999994, 'GSTP1': 3002.6, 'TLR2': 2486.0, 'TLR4': 780.2500000000001, 'TLR7': 872.05, 'TLR9': 7.6, 'STAT4': 51.5}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:41 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:41 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:41 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:41 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940493 in series GSE38351: {'MTHFR': 129.26, 'TYMS': 10.3, 'MTR': 203.55, 'MTRR': 169.8, 'CYP1A1': 1.4, 'GSTM1': 169.2, 'GSTT1': 53.1, 'GSTP1': 3082.5, 'TLR2': 3867.4, 'TLR4': 590.3000000000001, 'TLR7': 336.1, 'TLR9': 33.7, 'STAT4': 95.5}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:42 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:42 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:42 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:42 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940494 in series GSE38351: {'MTHFR': 91.68, 'TYMS': 8.200000000000001, 'MTR': 327.2, 'MTRR': 262.25, 'CYP1A1': 2.0, 'GSTM1': 76.25, 'GSTT1': 16.25, 'GSTP1': 3157.3, 'TLR2': 2244.6, 'TLR4': 709.7500000000001, 'TLR7': 964.05, 'TLR9': 35.0, 'STAT4': 101.4}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:43 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:43 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:43 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:43 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940495 in series GSE38351: {'MTHFR': 125.74000000000001, 'TYMS': 10.9, 'MTR': 193.95, 'MTRR': 205.0, 'CYP1A1': 5.9, 'GSTM1': 118.4, 'GSTT1': 48.75, 'GSTP1': 3977.7, 'TLR2': 6400.4, 'TLR4': 613.575, 'TLR7': 890.8, 'TLR9': 38.9, 'STAT4': 126.9}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:43 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:43 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:43 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:43 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940496 in series GSE38351: {'MTHFR': 150.5, 'TYMS': 12.366666666666665, 'MTR': 221.10000000000002, 'MTRR': 260.45, 'CYP1A1': 9.1, 'GSTM1': 284.35, 'GSTT1': 60.55, 'GSTP1': 3733.6, 'TLR2': 4483.4, 'TLR4': 607.525, 'TLR7': 587.7, 'TLR9': 31.7, 'STAT4': 100.0}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:44 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:44 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:44 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:44 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940497 in series GSE38351: {'MTHFR': 148.28, 'TYMS': 7.8, 'MTR': 184.25, 'MTRR': 293.75, 'CYP1A1': 4.8, 'GSTM1': 95.25, 'GSTT1': 9.450000000000001, 'GSTP1': 3762.2, 'TLR2': 4146.7, 'TLR4': 579.75, 'TLR7': 799.25, 'TLR9': 19.3, 'STAT4': 90.3}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:45 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:45 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:45 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:45 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940498 in series GSE38351: {'MTHFR': 166.84, 'TYMS': 5.1000000000000005, 'MTR': 205.95000000000002, 'MTRR': 286.15, 'CYP1A1': 16.2, 'GSTM1': 75.25, 'GSTT1': 52.85, 'GSTP1': 4421.9, 'TLR2': 4098.0, 'TLR4': 742.6, 'TLR7': 620.8, 'TLR9': 23.5, 'STAT4': 66.3}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:46 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:46 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:46 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:46 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940499 in series GSE38351: {'MTHFR': 169.37999999999997, 'TYMS': 8.766666666666667, 'MTR': 208.79999999999998, 'MTRR': 255.0, 'CYP1A1': 4.4, 'GSTM1': 138.7, 'GSTT1': 66.75, 'GSTP1': 3128.0, 'TLR2': 3920.4, 'TLR4': 841.375, 'TLR7': 299.75, 'TLR9': 27.1, 'STAT4': 68.7}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:47 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:47 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:47 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:47 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940500 in series GSE38351: {'MTHFR': 109.14000000000001, 'TYMS': 12.5, 'MTR': 279.85, 'MTRR': 233.8, 'CYP1A1': 7.6, 'GSTM1': 62.8, 'GSTT1': 8.15, 'GSTP1': 3991.6, 'TLR2': 3113.3, 'TLR4': 796.5, 'TLR7': 962.3, 'TLR9': 36.5, 'STAT4': 63.2}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:48 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:48 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:48 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:48 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940501 in series GSE38351: {'MTHFR': 189.45999999999998, 'TYMS': 8.433333333333334, 'MTR': 182.29999999999998, 'MTRR': 225.7, 'CYP1A1': 14.8, 'GSTM1': 123.94999999999999, 'GSTT1': 40.1, 'GSTP1': 3739.9, 'TLR2': 5506.0, 'TLR4': 665.575, 'TLR7': 551.3, 'TLR9': 14.6, 'STAT4': 61.9}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:48 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:48 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:48 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:48 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940502 in series GSE38351: {'MTHFR': 187.45999999999998, 'TYMS': 11.299999999999999, 'MTR': 159.8, 'MTRR': 248.15, 'CYP1A1': 9.5, 'GSTM1': 190.75, 'GSTT1': 27.2, 'GSTP1': 4167.2, 'TLR2': 4964.1, 'TLR4': 680.2750000000001, 'TLR7': 443.1, 'TLR9': 13.7, 'STAT4': 51.7}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:49 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:49 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:49 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:49 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940503 in series GSE38351: {'MTHFR': 233.4, 'TYMS': 9.466666666666667, 'MTR': 182.29999999999998, 'MTRR': 330.8, 'CYP1A1': 5.3, 'GSTM1': 262.05, 'GSTT1': 44.95, 'GSTP1': 3684.3, 'TLR2': 4516.4, 'TLR4': 794.825, 'TLR7': 377.5, 'TLR9': 23.1, 'STAT4': 58.9}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:50 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:50 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:50 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:50 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940504 in series GSE38351: {'MTHFR': 228.51999999999998, 'TYMS': 8.766666666666666, 'MTR': 184.8, 'MTRR': 351.3, 'CYP1A1': 10.2, 'GSTM1': 74.5, 'GSTT1': 7.5, 'GSTP1': 4076.0, 'TLR2': 4960.5, 'TLR4': 683.4499999999999, 'TLR7': 564.7, 'TLR9': 16.0, 'STAT4': 75.7}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:51 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:51 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:51 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:51 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940505 in series GSE38351: {'MTHFR': 128.21999999999997, 'TYMS': 6.866666666666667, 'MTR': 163.6, 'MTRR': 311.2, 'CYP1A1': 3.7, 'GSTM1': 364.4, 'GSTT1': 67.25, 'GSTP1': 2844.6, 'TLR2': 2684.8, 'TLR4': 733.1500000000001, 'TLR7': 299.15, 'TLR9': 38.8, 'STAT4': 43.9}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:52 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:52 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:52 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:52 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940506 in series GSE38351: {'MTHFR': 144.48, 'TYMS': 7.433333333333333, 'MTR': 220.45, 'MTRR': 255.10000000000002, 'CYP1A1': 5.1, 'GSTM1': 77.05000000000001, 'GSTT1': 52.0, 'GSTP1': 4161.6, 'TLR2': 2571.7, 'TLR4': 426.59999999999997, 'TLR7': 146.6, 'TLR9': 33.7, 'STAT4': 59.1}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:53 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:53 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:53 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:53 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940507 in series GSE38351: {'MTHFR': 104.47999999999999, 'TYMS': 4.766666666666667, 'MTR': 205.85, 'MTRR': 303.55, 'CYP1A1': 3.6, 'GSTM1': 53.8, 'GSTT1': 6.55, 'GSTP1': 3422.0, 'TLR2': 2953.9, 'TLR4': 610.125, 'TLR7': 171.65, 'TLR9': 27.3, 'STAT4': 180.1}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:53 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:53 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:53 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:53 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940508 in series GSE38351: {'MTHFR': 113.04, 'TYMS': 6.8999999999999995, 'MTR': 222.5, 'MTRR': 236.95, 'CYP1A1': 4.0, 'GSTM1': 80.95, 'GSTT1': 78.10000000000001, 'GSTP1': 4279.9, 'TLR2': 3787.5, 'TLR4': 567.875, 'TLR7': 323.1, 'TLR9': 16.2, 'STAT4': 57.8}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:54 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:54 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:54 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:54 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940509 in series GSE38351: {'MTHFR': 104.98000000000002, 'TYMS': 6.933333333333334, 'MTR': 206.7, 'MTRR': 321.4, 'CYP1A1': 10.6, 'GSTM1': 57.9, 'GSTT1': 36.400000000000006, 'GSTP1': 3638.8, 'TLR2': 2701.0, 'TLR4': 690.1999999999999, 'TLR7': 334.1, 'TLR9': 3.6, 'STAT4': 60.1}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")
14-Apr-2026 18:43:55 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:43:55 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:43:55 INFO GEOparse - Parsing ./GPL570.txt:
14-Apr-2026 18:43:55 DEBUG GEOparse - PLATFORM: GPL570

Gene expression for sample GSM940510 in series GSE38351: {'MTHFR': 70.42, 'TYMS': 15.666666666666666, 'MTR': 193.45, 'MTRR': 258.05, 'CYP1A1': 24.9, 'GSTM1': 99.35, 'GSTT1': 43.8, 'GSTP1': 3624.3, 'TLR2': 2530.5, 'TLR4': 701.3, 'TLR7': 296.8, 'TLR9': 20.2, 'STAT4': 38.7}

/home/aldis/.local/lib/python3.10/site-packages/GEOparse/GEOparse.py:401: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return read_csv(StringIO(data), index_col=None, sep="\t")

KeyboardInterrupt:

In [42]:
probe_id = "GPL10558"
probe = GEOparse.get_GEO(probe_id)

14-Apr-2026 18:55:52 DEBUG utils - Directory ./ already exists. Skipping.
14-Apr-2026 18:55:52 INFO GEOparse - File already exist: using local version.
14-Apr-2026 18:55:52 INFO GEOparse - Parsing ./GPL10558.txt:
14-Apr-2026 18:55:52 DEBUG GEOparse - PLATFORM: GPL10558

In [45]:
print(dir(probe))
probe.table.head()

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__metaclass__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_get_columns_as_string', '_get_metadata_as_string', '_get_object_as_soft', '_get_table_as_string', 'columns', 'database', 'geotype', 'get_accession', 'get_metadata_attribute', 'get_type', 'gses', 'gsms', 'head', 'metadata', 'name', 'relations', 'show_columns', 'show_metadata', 'show_table', 'table', 'to_soft']

,ID,Species,Source,Search_Key,Transcript,ILMN_Gene,Source_Reference_ID,RefSeq_ID,Unigene_ID,Entrez_Gene_ID,...,Probe_Chr_Orientation,Probe_Coordinates,Cytoband,Definition,Ontology_Component,Ontology_Process,Ontology_Function,Synonyms,Obsolete_Probe_Id,GB_ACC
0,ILMN_1343048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ILMN_1343049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ILMN_1343050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ILMN_1343052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ILMN_1343059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN